# See documentation at http://goreleaser.com
version: 2
builds:
  - main: ./cmd/xc
    id: xc
    binary: xc
    buildmode: "c-archive"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 6
brews:
  -
    ids:
      - brew
    goarm: 7
    repository:
      owner: joerdav
      name: homebrew-xc
    description: Self documenting task runner
    homepage: https://github.com/joerdav/xc
    license: "MIT"
signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]
archives:
  - format: binary
    id: xc
  - format: tar.gz
    id: brew
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
