runtime: python312

handlers:

- url: /
  static_files: public/index.html
  upload: public/*
- url: /(.*)/
  static_files: public/\1/index.html
  upload: public/(.*)
- url: /
  static_dir: public/
- url: /.*
  static_files: public/404.html
  upload: public/404.html
  error_code: 404
