runtime: python312
api_version: 1

handlers:

- url: /
  static_files: public/index.html
  upload: public/*
- url: /(.*)/
  static_files: public/\1/index.html
  upload: public/(.*)
- url: /
  static_dir: public/

